services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    attach: false
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - challenge-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes: ['rabbitmq_data:/var/lib/rabbitmq']


  # Postgres Database
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - challenge-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: task_manager_bd
  # Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: ./apps/auth-service  # ✅ Contexto específico do serviço
      dockerfile: dockerfile
      target: development
    ports:
      - '3002:3002'
    volumes:
      -  ./apps/auth-service:/app  # ✅ Montar volume
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=task_manager_bd
      - JWT_SECRET=96f35662f185ab2ac76b0d932516a5ba
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=df7bc93e81dc8a30e48bddd96b7e3bc2
      - JWT_REFRESH_EXPIRES_IN=7d
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:   
      - db
      - rabbitmq
    networks:
      - challenge-network


  # Notifications Service
  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
      target: development
    ports:
      - '3004:3004'
    volumes:
      - ./apps/notifications-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=task_manager_bd
      - JWT_SECRET=96f35662f185ab2ac76b0d932516a5ba
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=df7bc93e81dc8a30e48bddd96b7e3bc2
      - JWT_REFRESH_EXPIRES_IN=7d
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-network



  # Tasks Service
  tasks-service:
    container_name: tasks-service
    build:
      context: ./apps/tasks-service
      dockerfile: Dockerfile
      target: development
    ports:
      - '3003:3003'
    volumes:
      - ./apps/tasks-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=task_manager_bd
      - JWT_SECRET=96f35662f185ab2ac76b0d932516a5ba
      - JWT_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=df7bc93e81dc8a30e48bddd96b7e3bc2
      - JWT_REFRESH_EXPIRES_IN=7d
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - challenge-network



  # API Gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: ./apps/api-gateway
      dockerfile: Dockerfile
      target: development
    ports:
      - '3001:3001'
    volumes:
      - ./apps/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - auth-service
      - tasks-service
      - notifications-service
    networks:
      - challenge-network



volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  challenge-network:
    driver: bridge


